enableGlobalCache: true
nodeLinker: node-modules
npmRegistryServer: 'https://registry.yarnpkg.com'
npmScopes:
  kastelll:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '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'
